### ISSUE TITLE
_numConns unused

### ISSUE THREAD

**Issue by mulain** [pandaero/42_Core_webserv#4]
numconns is not used, and wont let the program compile

**Comment by pandaero** [comment]
we still have it and it works, is it still unnecessary?

**Comment by mulain** [comment]
Not sure if I understand your question correctly, but: We wanted _numConns as a counter to monitor for the max number of allowed connected clients. We hadn't implemented the counter function yet and this issue was supposed to serve as a reminder to eventually take of that and un-void the variable.

**Comment by pandaero** [comment]
to be turned to static variable (belonging to class) and used to restrict client connections
