### ISSUE TITLE
Exceptions have to be more descriptive

### ISSUE THREAD

**Issue by pandaero** [pandaero/42_Core_webserv#8]
Because the exceptions are generic, it is hard to determine where they are coming from:

<img width="1023" alt="Screen Shot 2023-04-27 at 5 49 38 PM" src="https://user-images.githubusercontent.com/46035129/234916796-3fa0a5b9-12ca-4d06-9181-7428ca29d211.png">

I'd encourage the use of nested exception classes, with traceable what() messages:

<img width="545" alt="Screen Shot 2023-04-27 at 5 51 07 PM" src="https://user-images.githubusercontent.com/46035129/234917158-2e5ed4ea-969f-4c1a-bea4-9406dbf12f83.png">

**Comment by mulain** [comment]
Hmm. I don't follow. What information are you missing in that example? It states the problem "can't read" and the actual input it received and that it can't read from "website/root". That's pretty on point, no?

**Comment by pandaero** [comment]
Yes, when I got the error, I had no idea where to look for the cause in the code!

**Comment by pandaero** [comment]
this is still an issue, looking at the ambiguous generic exceptions 👀
