### ISSUE TITLE
Default config should be parsed from a config file, not set in the code.

### ISSUE THREAD

**Issue by pandaero** [pandaero/42_Core_webserv#9]
For the "fallback" configuration, it should be a text file that can be easily edited, rather than parameters hard-coded into the source code of the program. This is because the default may evolve, as it just did because of the folder structure, and it requires re-writing of the hard-coded default, instead of changing a default config file.

Affected files:
src/ServerConfig.cpp

Affected functions:
::setDefault

**Comment by mulain** [comment]
Good idea!

**Comment by pandaero** [comment]
solved by #16
